// AUTO-GENERATED by scripts/sync-edison-assets.mjs — do not edit by hand.
// Lists every image present in public/edison. KenBurnsImage renders a procedural
// <ProceduralPlate> for any shot whose src is NOT in this set, so renders never
// break on a missing asset. Re-run `npm run edison:manifest` after adding images.
export const EDISON_ASSETS = new Set<string>([]);
